### ISSUE TITLE
AWS- Issue 

### ISSUE THREAD

**Issue by ShaneCupid** [TeamPhoneBook/contactApp#6]
"Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon May 02 17:31:16 UTC 2022
There was an unexpected error (type=Not Found, status=404)"

My database, eclipse, and AWS seem to connect however, when I click on the URL once my JAR file is uploaded I get the above error.

**Comment by ShaneCupid** [comment]
The issue was resolved once I deleted a column that was inserted via MySQL workbench. My table needed to be empty before proceeding with the Postman methods. Postman requests were preferred over MySQL to ensure everything ran smoothly.

**Comment by CcoleCode** [comment]
This issue has been solved.
